<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Services</title>

  <link rel="shortcut icon" type="image/x-icon" href="images/favicon.png" />
  <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">

  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
 <link rel="stylesheet" href="vendor/fontawesome/css/font-awesome.min.css">
  <link href="css/animate.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans&display=swap" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

  <link id="bodybg" href="bodybg/bg1.css" rel="stylesheet" type="text/css" />
 
  <link id="t-colors" href="color/default.css" rel="stylesheet">